### ISSUE TITLE
Script does not download ROMs for MRA files added by hand

### ISSUE THREAD

**Issue by bdlou** [MAME-GETTER/MiSTer_MAME_SCRIPTS#30] opened 2021-04-12 13:30 UTC
Constant support issues come up when people add MRA files to their MiSTer by hand (Example: Patreon cores in beta), rather than pulling them down with the update_all script. Users are having to be guided through how to remove the last run file to get the script to pick up the manually added MRA files .

**Comment by MAME-GETTER** [comment] 2021-06-02 19:08
Mame-Getter finds MRAs that are place in /media/fat/_Arcade/*

if you ever have to remove the last run file to get the script to pick up roms then your doing something wrong. 

Closing

**Closed by MAME-GETTER** 2021-06-02 19:08 UTC

**Comment by MJY71** [comment] 2021-06-02 20:15
Surely you must be aware of the numerous support instances in JT's Discord server where users have reported this problem, and the method above mentioned to users by both bdlou and myself has been the solution every time. There is very little that can go wrong with simply copying MRAs manually from a zip file to the root of the _Arcade folder. Sure, one or two people, perhaps... but this has been several more than that. The simple fact is, the script is not always finding the newest MRAs that are placed in that folder. If removing the last run file allows the script to see the MRAs and download the additional ROMs, it means the MRAs were in the correct location all along.

**Comment by theypsilon** [comment] 2021-06-03 23:20
I suspect the root cause of these issues could be happening because the attributes of the files are being handled incorrectly during the copy. In order to track that possible scenario, it would be helpful to get more info about what tools and platforms are being used during the copy of the files. We would need to find a deterministic way to reproduce that problem, otherwise is impossible to do anything in our end.

**Comment by MJY71** [comment] 2021-06-04 00:02
I agree. However, if it's an attribute problem, how does deleting the last run file and re-running the script change any of that? The MRAs still have the same attributes on the SD card, I would assume. What we found (based on another user's recommendations in JT's Patreon) was that doing so allowed the script to scan all of the MRAs, including the newer manually-copied files, without the users changing anything else on their end.

**Comment by theypsilon** [comment] 2021-06-04 07:35
That is because the file attributes regarding time are only considered during a non-fresh run:

```
if [[ "${FROM_SCRATCH}" == "false" ]] ; then    
              FIND_ARGS+=(-newerct ${LAST_MRA_DATE})
fi
```

If that file is missing, the run is made from scratch.

Because this is a FAT32 filesystem under Linux, I wouldn't be surprised if some creation/modification time attributes are not handled correctly by some tooling.

I will add a "force full resync" option to MAME and HBMAME Getter submenus in Update All's Setting Screen, in order to improve a bit the UX in the meantime.

**Comment by MJY71** [comment] 2021-06-04 11:07
Thanks. I figured with the final CPS-2 beta being released, there wouldn't be a good opportunity to test that again soon, but there should be a new batch of Sega System 16 MRAs released soon, so fingers crossed.
